# fly.toml app configuration file

app = 'chatbot-backend-wandering-shadow-534'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 10000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  # Health check configuration
  [[http_service.checks]]
    grace_period = "15s"
    interval = "15s"
    method = "GET"
    timeout = "5s"
    path = "/ping"

[processes]
  app = "gunicorn --config gunicorn_config.py app:app"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1